
# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
  
gems:
  - jekyll-relative-links

baseurl: "/abc"
url: "https://karagk.github.io/abc"
